# Generated by Django 3.0.5 on 2020-04-16 15:03

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200409_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='logo',
            field=models.FileField(blank=True, help_text='Upload your company logo', null=True, upload_to=users.models.avatar_directory_path),
        ),
    ]
