# Generated by Django 3.0.5 on 2020-04-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200416_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
