# Generated by Django 3.0.5 on 2020-04-20 08:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200416_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='This is your login email.  Careful on changing this field.', max_length=255, unique=True, validators=[django.core.validators.MaxLengthValidator(80)]),
        ),
    ]
