# Generated by Django 3.0.5 on 2020-04-09 05:40

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200409_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
