# Generated by Django 3.0.5 on 2020-04-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='email',
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
