# Generated by Django 3.0.5 on 2020-04-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(max_length=300, null=True, unique=True),
        ),
    ]
