# Generated by Django 3.0.5 on 2020-04-14 11:23

from django.db import migrations, models
import django.db.models.deletion
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_job_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=jobs.models.applicant_directory_path),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_application_email',
            field=models.EmailField(blank=True, help_text='Notify this email or blank to use default email', max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_link',
            field=models.URLField(blank=True, help_text='Enter external link or use our cover letter system', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=200, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_range',
            field=models.CharField(blank=True, help_text='Example:  $1000-2000 or $40 per hour', max_length=200, null=True, verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_environment',
            field=models.CharField(choices=[('remote', 'Remote'), ('flexible', 'Flexible'), ('onsite', 'On Site')], max_length=50, verbose_name='Environment'),
        ),
        migrations.CreateModel(
            name='ApplicantAnwer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jobs.Applicant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='jobs.JobQuestion')),
            ],
        ),
    ]
