# Generated by Django 3.0.5 on 2020-04-15 03:35

from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20200414_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='cover_letter',
            field=models.TextField(verbose_name='Cover Letter'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='document',
            field=models.FileField(blank=True, help_text='Upload your resume or any supporting document', null=True, upload_to=jobs.models.applicant_directory_path),
        ),
        migrations.AlterUniqueTogether(
            name='applicant',
            unique_together={('job', 'email')},
        ),
    ]
