# Generated by Django 3.0.5 on 2020-04-15 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_auto_20200415_0335'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicant',
            unique_together=set(),
        ),
    ]
