# Generated by Django 3.0.5 on 2020-04-15 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_auto_20200415_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantanwer',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Applicant'),
        ),
        migrations.AlterField(
            model_name='applicantanwer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.JobQuestion'),
        ),
        migrations.AlterUniqueTogether(
            name='applicant',
            unique_together={('job', 'email')},
        ),
    ]
