# Generated by Django 3.0.5 on 2020-04-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_auto_20200415_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='applicant_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('interview', 'Interview'), ('hire', 'Hire')], max_length=50),
        ),
    ]
