# Generated by Django 3.0.5 on 2020-04-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_auto_20200416_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='expired_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
